"""Canonical OSIS-style book registry for Knowledge Base references."""

from __future__ import annotations

from dataclasses import dataclass


@dataclass(frozen=True)
class BookRecord:
    """Stable internal book identity (OSIS-like id)."""

    osis_id: str
    ruf_code: str
    testament: str  # OT | NT
    single_chapter: bool = False


# Primary registry: OSIS id is the canonical internal book code.
BOOKS: tuple[BookRecord, ...] = (
    BookRecord("Gen", "GEN", "OT"),
    BookRecord("Exod", "EXO", "OT"),
    BookRecord("Lev", "LEV", "OT"),
    BookRecord("Num", "NUM", "OT"),
    BookRecord("Deut", "DEU", "OT"),
    BookRecord("Josh", "JOS", "OT"),
    BookRecord("Judg", "JDG", "OT"),
    BookRecord("Ruth", "RUT", "OT"),
    BookRecord("1Sam", "1SA", "OT"),
    BookRecord("2Sam", "2SA", "OT"),
    BookRecord("1Kgs", "1KI", "OT"),
    BookRecord("2Kgs", "2KI", "OT"),
    BookRecord("1Chr", "1CH", "OT"),
    BookRecord("2Chr", "2CH", "OT"),
    BookRecord("Ezra", "EZR", "OT"),
    BookRecord("Neh", "NEH", "OT"),
    BookRecord("Esth", "EST", "OT"),
    BookRecord("Job", "JOB", "OT"),
    BookRecord("Ps", "PSA", "OT"),
    BookRecord("Prov", "PRO", "OT"),
    BookRecord("Eccl", "ECC", "OT"),
    BookRecord("Song", "SNG", "OT"),
    BookRecord("Isa", "ISA", "OT"),
    BookRecord("Jer", "JER", "OT"),
    BookRecord("Lam", "LAM", "OT"),
    BookRecord("Ezek", "EZK", "OT"),
    BookRecord("Dan", "DAN", "OT"),
    BookRecord("Hos", "HOS", "OT"),
    BookRecord("Joel", "JOL", "OT"),
    BookRecord("Amos", "AMO", "OT"),
    BookRecord("Obad", "OBA", "OT", single_chapter=True),
    BookRecord("Jonah", "JON", "OT"),
    BookRecord("Mic", "MIC", "OT"),
    BookRecord("Nah", "NAM", "OT"),
    BookRecord("Hab", "HAB", "OT"),
    BookRecord("Zeph", "ZEP", "OT"),
    BookRecord("Hag", "HAG", "OT"),
    BookRecord("Zech", "ZEC", "OT"),
    BookRecord("Mal", "MAL", "OT"),
    BookRecord("Matt", "MAT", "NT"),
    BookRecord("Mark", "MRK", "NT"),
    BookRecord("Luke", "LUK", "NT"),
    BookRecord("John", "JHN", "NT"),
    BookRecord("Acts", "ACT", "NT"),
    BookRecord("Rom", "ROM", "NT"),
    BookRecord("1Cor", "1CO", "NT"),
    BookRecord("2Cor", "2CO", "NT"),
    BookRecord("Gal", "GAL", "NT"),
    BookRecord("Eph", "EPH", "NT"),
    BookRecord("Phil", "PHP", "NT"),
    BookRecord("Col", "COL", "NT"),
    BookRecord("1Thess", "1TH", "NT"),
    BookRecord("2Thess", "2TH", "NT"),
    BookRecord("1Tim", "1TI", "NT"),
    BookRecord("2Tim", "2TI", "NT"),
    BookRecord("Titus", "TIT", "NT"),
    BookRecord("Phlm", "PHM", "NT", single_chapter=True),
    BookRecord("Heb", "HEB", "NT"),
    BookRecord("Jas", "JAS", "NT"),
    BookRecord("1Pet", "1PE", "NT"),
    BookRecord("2Pet", "2PE", "NT"),
    BookRecord("1John", "1JN", "NT"),
    BookRecord("2John", "2JN", "NT", single_chapter=True),
    BookRecord("3John", "3JN", "NT", single_chapter=True),
    BookRecord("Jude", "JUD", "NT", single_chapter=True),
    BookRecord("Rev", "REV", "NT"),
)

OSIS_BY_ID: dict[str, BookRecord] = {book.osis_id: book for book in BOOKS}
RUF_TO_OSIS: dict[str, str] = {book.ruf_code: book.osis_id for book in BOOKS}

# English display aliases commonly used in imports (OpenBible OSIS uses full names).
ENGLISH_OSIS_ALIASES: dict[str, str] = {
    "Genesis": "Gen",
    "Exodus": "Exod",
    "Leviticus": "Lev",
    "Numbers": "Num",
    "Deuteronomy": "Deut",
    "Joshua": "Josh",
    "Judges": "Judg",
    "Ruth": "Ruth",
    "1Samuel": "1Sam",
    "2Samuel": "2Sam",
    "1Kings": "1Kgs",
    "2Kings": "2Kgs",
    "1Chronicles": "1Chr",
    "2Chronicles": "2Chr",
    "Ezra": "Ezra",
    "Nehemiah": "Neh",
    "Esther": "Esth",
    "Job": "Job",
    "Psalm": "Ps",
    "Psalms": "Ps",
    "Proverbs": "Prov",
    "Ecclesiastes": "Eccl",
    "SongOfSongs": "Song",
    "Song": "Song",
    "Isaiah": "Isa",
    "Jeremiah": "Jer",
    "Lamentations": "Lam",
    "Ezekiel": "Ezek",
    "Daniel": "Dan",
    "Hosea": "Hos",
    "Joel": "Joel",
    "Amos": "Amos",
    "Obadiah": "Obad",
    "Jonah": "Jonah",
    "Micah": "Mic",
    "Nahum": "Nah",
    "Habakkuk": "Hab",
    "Zephaniah": "Zeph",
    "Haggai": "Hag",
    "Zechariah": "Zech",
    "Malachi": "Mal",
    "Matthew": "Matt",
    "Mark": "Mark",
    "Luke": "Luke",
    "John": "John",
    "Acts": "Acts",
    "Romans": "Rom",
    "1Corinthians": "1Cor",
    "2Corinthians": "2Cor",
    "Galatians": "Gal",
    "Ephesians": "Eph",
    "Philippians": "Phil",
    "Colossians": "Col",
    "1Thessalonians": "1Thess",
    "2Thessalonians": "2Thess",
    "1Timothy": "1Tim",
    "2Timothy": "2Tim",
    "Titus": "Titus",
    "Philemon": "Phlm",
    "Hebrews": "Heb",
    "James": "Jas",
    "1Peter": "1Pet",
    "2Peter": "2Pet",
    "1John": "1John",
    "2John": "2John",
    "3John": "3John",
    "Jude": "Jude",
    "Revelation": "Rev",
}
